name: Update API Documentation on Bump.sh

on:
  push:
    branches: [ main, master ]
    paths:
      - 'src/**'
      - 'pom.xml'
  workflow_dispatch:

jobs:
  deploy-doc:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Cache Maven packages
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
        
    - name: Build application
      run: ./mvnw clean compile
      
    - name: Start application for OpenAPI generation
      run: |
        ./mvnw spring-boot:run &
        echo $! > app.pid
        sleep 30  # Wait for application to start
        
    - name: Generate OpenAPI specification
      run: |
        # Wait for application to be ready
        while ! curl -f http://localhost:8080/actuator/health 2>/dev/null; do
          echo "Waiting for application to start..."
          sleep 5
        done
        
        # Download OpenAPI spec
        curl -o openapi.json http://localhost:8080/api-docs
        
    - name: Stop application
      run: |
        if [ -f app.pid ]; then
          kill $(cat app.pid) || true
          rm app.pid
        fi
        
    - name: Deploy to Bump.sh
      uses: bump-sh/github-action@v1
      with:
        doc: ${{ secrets.BUMP_DOC_ID }}
        token: ${{ secrets.BUMP_TOKEN }}
        file: openapi.json
        
    - name: Upload OpenAPI spec as artifact
      uses: actions/upload-artifact@v3
      with:
        name: openapi-spec
        path: openapi.json
