name: Update API Documentation on Bump.sh

on:
  push:
    branches: [ main, master ]
    paths:
      - 'backend/src/**'
      - 'backend/pom.xml'
      - 'backend/openapi.json'
  workflow_dispatch:

jobs:
  deploy-doc:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Cache Maven packages
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
        
    - name: Build application
      working-directory: backend
      run: ./mvnw clean compile
      
    - name: Start application for OpenAPI generation
      working-directory: backend
      run: |
        ./mvnw spring-boot:run &
        echo $! > app.pid
        sleep 45  # Wait for application to start
        
    - name: Generate OpenAPI specification
      working-directory: backend
      run: |
        # Wait for application to be ready
        max_attempts=30
        attempt=0
        while [ $attempt -lt $max_attempts ]; do
          if curl -f http://localhost:8080/actuator/health 2>/dev/null; then
            echo "Application is ready!"
            break
          fi
          echo "Waiting for application to start... (attempt $((attempt + 1))/$max_attempts)"
          sleep 5
          attempt=$((attempt + 1))
        done
        
        if [ $attempt -eq $max_attempts ]; then
          echo "Application failed to start within expected time"
          exit 1
        fi
        
        # Download OpenAPI spec
        curl -o openapi.json http://localhost:8080/api-docs
        
    - name: Stop application
      working-directory: backend
      run: |
        if [ -f app.pid ]; then
          kill $(cat app.pid) || true
          rm app.pid
        fi
        
    - name: Deploy to Bump.sh
      uses: bump-sh/github-action@v1
      with:
        doc: ${{ secrets.BUMP_DOC_ID }}
        token: ${{ secrets.BUMP_TOKEN }}
        file: backend/openapi.json
        
    - name: Upload OpenAPI spec as artifact
      uses: actions/upload-artifact@v3
      with:
        name: openapi-spec
        path: backend/openapi.json
